name: Stag CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Build and Test
        run: |
          # Add your build and test commands here
          echo "Building and testing the application"

      - name: Deploy to VPS
        env:
          SSH_USER: ${{ secrets.VPS_USER }}
          SSH_PASS: ${{ secrets.VPS_PASSWORD }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$VPS_IP << 'EOF'
            cd /root/stage/FE
            git pull origin dev
            pnpm install
            NODE_OPTIONS="--max_old_space_size=4096" npm run build
            cd build
            cp -r * /var/www/stagefe
          EOF
